ERROR_CODE_NOT_SUPPORT = -101
ERROR_CODE_FILE_NOT_EXISTS = -102
ERROR_CODE_FILE_INVALID = -103
ERROR_CODE_NO_SPEECH = -104
ERROR_CODE_MEDIA_FORMAT_CONVERT_ERROR = -105
ERROR_CODE_MEDIA_FILE_TOO_SHORT = -106
ERROR_CODE_FILE_DOWNLOAD_FAILED = -107


ERROR_CODE_NO_VALID_LANGUAGE = -201